### ISSUE TITLE
Improve readme Quick Start with a typescript option

### ISSUE THREAD

**Issue by bwswedberg** [schibsted/jsx-pdf#30]
Thanks for the helpful lib! It would be nice if the Quick Start section of your docs had a typescript portion. Since you don't need babel if you are using typescript. I was able to successfully use jsx-pdf with typescript by naming the files with `.tsx` extension and adding the following to my tsconfig.json:
```
...
"compilerOptions": {
  "jsx": "react", // <- required
  "jsxFactory": "JsxPdf.createElement",
  ...
},
...
```

or skip the "jsxFactory" option in tsconfig.json and specify the jsxFactory at the top of every `.tsx` file that uses jsx-pdf with the following:
```
/** @jsx JsxPdf.createElement */
import JsxPdf from 'jsx-pdf';
...
```

**Comment by mtlewis** [comment]
Hey @bwswedberg - this is a great suggestion! Feel free to send a PR if you have time, otherwise I’ll try to get to it soon. Thanks!
