### ISSUE TITLE
Support for svg

### ISSUE THREAD

**Issue by bwswedberg** [schibsted/jsx-pdf#34]
Is it possible to support svg since pdfmake supports it? Like, https://pdfmake.github.io/docs/document-definition-object/svgs/

Anyways, thanks a ton for the library. It has been very helpful in working with pdfmake. Keep up the awesome work!!

**Comment by mtlewis** [comment]
Hey @bwswedberg - thanks for the request, glad to hear the library is useful for you. As you say, adding support for SVG seems to be simple - I've added it in #36. Once that and #32 are merged, v2.2.0 will land with SVG support included.
