### ISSUE TITLE
Move to travis-ci.com

### ISSUE THREAD

**Issue by mtlewis** [schibsted/jsx-pdf#56]
Looks like we need an owner of the Schibsted org to make some changes to handle the move from travis-ci.org to travis-ci.com. See the migration docs here: https://docs.travis-ci.com/user/migrate/open-source-repository-migration/. Until this is done, I don't think new CI builds will run.

AFAIK, everyone that actively contributes to this project is now an outside collaborator, since we've all moved on from Schibsted. Tagging a couple of folks who seem to still be in the Schibsted org: @forberg, @paugay.

**Comment by rob-mccann** [comment]
A couple of other potential options:

- Could we move to Github Actions/do we still have the right access?
- Could we move to a separate org?
  - Along those lines, could we have Schibsted's blessing to move this out of their licence/copyright?
